name: Keka Web Clocking Automation

on:
  schedule:
    # 8:00 AM IST (2:30 AM UTC) Monday–Friday
    - cron: '30 2 * * 1-5'
    # 8:00 PM IST (2:30 PM UTC) Monday–Friday
    - cron: '30 14 * * 1-5'
  workflow_dispatch:  # allows manual run from Actions tab

jobs:
  keka-clocking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install python-dotenv

      - name: Run Keka script
        env:
          KEKA_USERNAME: ${{ secrets.KEKA_USERNAME }}
          KEKA_PASSWORD: ${{ secrets.KEKA_PASSWORD }}
          KEKA_URL: ${{ secrets.KEKA_URL }}
        run: python keka_script.py
